### ISSUE TITLE
Not Available in NPM

### ISSUE THREAD

**Issue by eugenefedoto** [zang-cloud/zang-node#1]
Issue: the zang-node package can't be installed through the 'npm install zang-node' command because it's not in the NPM repository. 

Suggestions: 
a) Make a note in the README.md stating it's currently not possible to install through NPM, and instead for the user to include the package directly from the source files.

b) Create an NPM package, then upload it to www.npmjs.com.

**Comment by 0x19** [comment]
@eugenefedoto thank you for spotting that!

it's now available at:
https://www.npmjs.com/package/zang-node

Best,
